Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"

  # gateway
  config.vm.define "lb01" do |lb|
    lb.vm.hostname = "lb01"
    lb.vm.network "private_network", ip: "192.168.56.10"
    lb.vm.provider "virtualbox" do |v|
      v.memory = 512 # LB doesn't need much RAM
    end
  end

  # compute nodes
  ["compute01", "compute02"].each_with_index do |name, i|
    config.vm.define name do |node|
      node.vm.hostname = name
      node.vm.network "private_network", ip: "192.168.56.#{11 + i}"
      node.vm.provider "virtualbox" do |v|
        v.memory = 1024 # Compute needs more RAM for isolated processes
      end
    end
  end

  # storage nodes
  ["storage01", "storage02"].each_with_index do |name, i|
    config.vm.define name do |node|
      node.vm.hostname = name
      node.vm.network "private_network", ip: "192.168.56.#{13 + i}"
      node.vm.provider "virtualbox" do |v|
        v.memory = 512
      end
    end
  end

  # Sync your project folder to all nodes
  config.vm.synced_folder "../../", "/home/vagrant/cloud"
end